config/routes.rb
Rails.application.routes.draw do
  root 'topics#index'

  resources :topics, only: [:index, :new, :create] do
    member do
      patch 'upvote', to: 'topics#upvote'
      patch 'downvote', to: 'topics#downvote'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  votes      :integer          default("0"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_topics_on_title  (title) UNIQUE
#  index_topics_on_votes  (votes)
#

class Topic < ApplicationRecord
  validates :title, presence: true, uniqueness: true, length: { maximum: 255 }
  validates :votes, presence: true

  before_validation do
    # Set default votes
    self.votes ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.order(votes: :desc).limit(20)
  end

  def new
    @topic = Topic.new
  end

  def create
    topic = Topic.new(topic_params)

    if topic.save
      redirect_to topics_path
    else
      render :new
    end
  end

  def upvote
    topic = Topic.find params[:id]
    topic.update(votes: topic.votes + 1)
    redirect_to topics_path
  end

  def downvote
    topic = Topic.find params[:id]
    topic.update(votes: topic.votes - 1)
    redirect_to topics_path
  end

  private

  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/topics/index.html.haml
.container
  %h1 All Topics
  = link_to 'New Topic', new_topic_path, class: 'btn btn-default'
  %table.table
    %thead
      %th Title
      %th Votes
      %th Upvote
      %th Downvote
    %tbody
    - @topics.each do |t|
      %tr
        %td= t.title
        %td= t.votes
        %td= link_to "Upvote", upvote_topic_path(t), method: :patch
        %td= link_to "Downvote", downvote_topic_path(t), method: :patch

app/views/topics/new.html.haml
.container
  %h1 New Topic

  = form_for :topic, url: topics_path, html: { class: 'form-horizontal' } do |f|
    .form-group
      = f.label :title, class: 'col-sm-2'
      .col-sm-4
        = f.text_field :title, class: 'form-control'

    = f.submit 'Submit', class: 'btn', class: 'btn btn-primary'